[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.29"
optimizer = true
optimizer_runs = 200
evm_version = 'london'

[profile.assertions]
src = "assertions/src"
out = "assertions/out"
libs = ["lib"]
solc_version = "0.8.29"
optimizer = true
optimizer_runs = 200
gas_reports = ["*"]
test = "assertions/test"
